### ISSUE TITLE
wiki not found

### ISSUE THREAD

**Issue by mbaykara** [lowleveldesign/wtrace#12]
the linked **wiki** is blank. Does any wiki page exist?

**Comment by lowleveldesign** [comment]
Hi! Thanks for reporting the problem. You caught me in a middle of releasing a new version of wtrace 😅 The new wtrace documentation page is here: https://wtrace.net/documentation/wtrace/. And today I will update the README and merge the new code into the main branch.

**Comment by mbaykara** [comment]
Thanks for the quick response :)
