### ISSUE TITLE
Feature request: autoupdates

### ISSUE THREAD

**Issue by vchirikov** [lowleveldesign/wtrace#13]
Hi, thanks for the tool.

It will be nice to get autoupdates via [squirrel](https://github.com/Squirrel/Squirrel.Windows) or [choco](https://chocolatey.org) etc.

**Comment by lowleveldesign** [comment]
It took me a while, but I published the wtrace package to chocolatey repository: <https://community.chocolatey.org/packages/wtrace/3.1.21167.4>. Once they accept it, I will release updates. I'm closing this ticket as I have no control over how long the moderation takes (apparently it's not a quick operation :disappointed:).
