### ISSUE TITLE
Add support for decoding Windows 10 TraceLogging API events

### ISSUE THREAD

**Issue by Alan-Jowett** [lowleveldesign/wtrace#16]
Windows 10 introduced a new ETW event type that is manifest less called [TraceLogging](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/tracelogging-api).

It would useful if wtrace added support for capturing and viewing this new type of ETW event.

**Comment by lowleveldesign** [comment]
Hi Alan, thank you for the suggestion. Do you have any specific providers in mind? I'm leaning towards adding only particular events that may be useful in troubleshooting. Adding generic support for events will complicate wtrace usage, making it similar to xperf or wpr (which are the tools I would recommend to anyone looking for generic events collectors). I want to avoid that and keep the wtrace command line as simple as possible. Therefore, I want to support only specific (hard-coded) diagnostics scenarios (currently, these include: File I/O, Registry, RPC, TCP, UDP).

**Comment by Alan-Jowett** [comment]
Thanks for responding. Mostly I was looking for a way to solve https://github.com/microsoft/ebpf-for-windows/issues/795 and was hoping for something similar to ```sudo cat  /sys/kernel/debug/tracing/trace_pipe``` on Linux.

As it turns out, [tracelog](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/tracelog) and [tracefmt](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/tracefmt) have an ```-rt``` options, which gives me the functionality I was looking for, albeit in a somewhat quirky manner. We will probably end up just wrapping these in a script and calling it good enough. 

I agree that if you are looking to target specific ETW providers, then this request probably doesn't make as much sense.

**Comment by lowleveldesign** [comment]
Thanks for the explanation. I will close this ticket then.

And I must say I'm a big fan of the work you're doing with ebpf on Windows and can't wait to start playing with it. I have limited experience with the ebpf library on Linux and plan to spend more time learning and using it. The whole idea is amazing and provides new ways of troubleshooting 😊.
