### ISSUE TITLE
Is there a way to associate rpcclientcall with rpcservercall？

### ISSUE THREAD

**Issue by lmou523** [lowleveldesign/wtrace#17]
I saw your previous question on stackoverflow, but you didn't seem to find a good solution
I've just seen a way to do this with ActivityId
![image](https://github.com/lowleveldesign/wtrace/assets/59944420/1ab2c7d5-c2d1-4190-babd-01dd3ef612cc)
Here's the link to the original article:
https://www.elastic.co/cn/security-labs/effective-parenting-detecting-lrpc-based-parent-pid-spoofing

**Comment by lowleveldesign** [comment]
Thank you for letting me know! It's indeed very interesting. I need to find some time to run tests on my own, but it looks promising.

**Comment by lowleveldesign** [comment]
I don't think there is much more I can extract from the RPC ETW event. I am already using the ActivityIDs to correlate the RPC calls: https://github.com/lowleveldesign/wtrace/blob/master/wtrace.cmd/Events/Rpc.fs#L37. My original plan was to log only the end call, but after testing, I decided that logging both the start and end event is more informative, especially for long RPC calls. I am going to close this issue then, but thank you for the article - it is very informative.
