### ISSUE TITLE
Trying to diagnose why wbadmin crashes, wtrace reports error.

### ISSUE THREAD

**Issue by AaronFriel** [lowleveldesign/wtrace#3]
```
C:\WINDOWS\system32>"C:\Program Files\Sysinternals\wtrace.exe" C:\Windows\system32\wbadmin.exe
ERROR: an error occurred while trying to start or open the process, hr: 0x80004005, code: 0x00000002 (The system cannot find the file specified).
```

**Comment by AaronFriel** [comment]
Weirdly, if I copy `wbadmin.exe` to another folder, and run `wtrace` in that folder, it works fine.

**Comment by lowleveldesign** [comment]
Hi Aaron, thanks for reporting this problem. It looks like the Release build had the Prefer 32-bit set, which caused wtrace to start by default in the 32-bit mode and in consequence resolve paths according to the 32-bit rules. wbadmin.exe is available only in the C:\Windows\System32 folder (and missing in the C:\Windows\SysWOW64 folder) so 32-bit wtrace could not see it. As a workaround you could have used C:\Windows\sysnative\wbadmin.exe, which always maps to the 64-bit System32 folder.

I updated the binaries of the 1.3 release - it should work fine now.

**Comment by AaronFriel** [comment]
Today I learned about C:\Windows\sysnative existing as a virtual directory for 32-bit applications.
