### ISSUE TITLE
How do I listen for CreateProcess

### ISSUE THREAD

**Issue by cool-RR** [lowleveldesign/wtrace#9]
Thank you for creating wtrace! I'm trying to use it instead of Procmon, which is a GUI program, and using a CLI is much more convenient for many tasks.

In Procmon I'm able to see CreateProcess events, so I could for example wait for a Python program to be launched, and then get its command line arguments. How can I do this using wtrace? I'm not sure which arguments I should give wtrace, since my process doesn't exist yet.

**Comment by lowleveldesign** [comment]
wtrace filters the events by a process id so it won't show you all the processes that start in the system. But you may attach wtrace to a parent process (let's assume it is cmd.exe with pid 1234) and use the **-c** option to trace its child processes. If you want to see only the CreateProcess events use the **--filter** option, for example:

```
wtrace --filter Process/Start -c 1234
```

**Comment by cool-RR** [comment]
Works, thank you!
